# Consolidated feature inventory for BUILD-PLAN.md Appendix A.
# (domain, feature, final_status, package, source_rows)
# Status after challenge corrections. Duplicates across reports are merged; sources list every origin row.
R = []
def r(domain, feature, status, pkg, src):
    R.append((domain, feature, status, pkg, src))

D = "Shell & navigation"
r(D, "Title + 'Game vX · Console vY' version line", "MISSING", "S1", "01-A1")
r(D, "Console-update '!' indicator in header", "MISSING", "S1", "01-A2")
r(D, "Mail entry with unread count badge", "PARTIAL", "F4", "01-A3, 06-#43")
r(D, "Header entries Catalog/Bestiary/Skills/View market/Inspect bank", "PRESENT", "-", "01-A4, 06-#1, 06-#62, 06-#83, 05-K1")
r(D, "Inspect stand · N/16 occupied-slot count (occupiedStandSlots)", "BROKEN", "M4", "01-A5, 05-I1")
r(D, "Logs entry", "PRESENT", "-", "01-A6")
r(D, "Account screens reachable with no character online (home gear opens server override; AccountMenu only on character detail)", "UNREACHABLE", "F4", "01-A7, 01-ch confirmed #2, 01-O8, 02-oos")
r(D, "Settings gear seeds realm destination + ALData key auto-reveal", "PARTIAL", "F4", "01-A7")
r(D, "/wtb, /routines, /hunt-settings reachable from account menu", "PARTIAL", "F4", "01-O8, 05-L11")
r(D, "Party gold: bank + combined total, active non-bankboi slots, '—' when unknown, exact tooltip", "PARTIAL", "S1", "01-A8, 05-F1")
r(D, "abbreviatedGold formatting (1.234m / 123.4K)", "MISSING", "S1", "05-F2")
r(D, "Debug-instance banner + 'Open game client' link", "MISSING", "S2", "01-A9")
r(D, "Session-expired screen with Reconnect on 401/403/redirect", "BROKEN", "P0-02", "01-A10 (upgraded), 01-ch X1")
r(D, "Account-switch detection resets caches (accountId)", "MISSING", "F8", "01-A11")
r(D, "Global render-error page with retry/reload (error boundary)", "MISSING", "F4", "01-A12")
r(D, "'Couldn't complete action' error surface (toast equivalent)", "PRESENT", "-", "01-A13, 06-#95")
r(D, "Workspace load/reconnecting/empty states + 'open setup' link", "PARTIAL", "S1", "01-A14")
r(D, "WebMCP document.modelContext tools", "N/A", "-", "01-A15")
r(D, "DashboardModeControl / DashboardHealth (dead code)", "N/A", "-", "01-A16")

D = "Live data layer"
r(D, "SSE /dashboard-stream snapshot/delta/heartbeat receiver", "PRESENT", "-", "01-B1, 01-M5")
r(D, "Envelope validation (isSafeInteger(sequence), epoch string)", "PARTIAL", "P0-02", "01-B2, 01-BROKEN-8")
r(D, "Heartbeat watchdog + reconnect", "PRESENT", "-", "01-B3")
r(D, "Fixed-length inventory from vitals.inventorySize", "PRESENT", "-", "01-B5")
r(D, "Polling fallback (section=fast / section=inventory) while SSE unhealthy", "MISSING", "F8", "01-B6")
r(D, "Domain cadences (core 1s, config 15s, logs 1s, bank 2s, mail 2s, market 10s, catalog on referenceRevision)", "PARTIAL", "F8", "01-B7")
r(D, "Config domain GET /state?section=config fetched and merged", "BROKEN", "P0-01", "01-B8, 02-ch M1, 04-B1, 05-BR-1, 05-ch X1, 06-ch M1")
r(D, "Startup full GET /state parsed for roster only, config thrown away", "BROKEN", "P0-01", "05-ch X2")
r(D, "Roster kept fresh (from config, 15s)", "BROKEN", "P0-01", "01-B9")
r(D, "Bank section fetched with dashboard=1 (full bankboi records with items)", "BROKEN", "P0-01", "01-M1 bank row, 01-O7, 04-ch M1, 06-ch M2")
r(D, "characterDetails kept (diagnostics + presence), not reduced to monsterHunt", "PARTIAL", "F2", "01-B10, 02-top4, 03-ch (e)")
r(D, "serverNow clock-skew reference", "MISSING", "F2", "01-ch X7")
r(D, "Poll loops survive non-JSON / redirected responses (unguarded JSON.parse kills polling)", "BROKEN", "P0-02", "01-ch X1")
r(D, "Live metrics (window.dashboardLiveMetrics)", "N/A", "-", "01-B12")
r(D, "POST /aldata/refresh (no v1.2.0 caller)", "N/A", "-", "01-M1")
r(D, "/steam/action headless-all (no UI caller)", "N/A", "-", "01-ch matrix")

D = "Roster & sessions"
r(D, "Character list = activeSlots order, bankbois excluded, primary→Steam→headless→merchant", "PARTIAL", "R1", "01-C1")
r(D, "Offline / reconnecting character keeps a card (removal nulls vitals only)", "PARTIAL", "R1", "01-B4")
r(D, "'Load character slot N' buttons (disabled during Steam switch)", "MISSING", "R1", "01-C2")
r(D, "Roster picker (Headless/Steam toggle, hides active, 'Lv N class', empty text)", "MISSING", "R1", "01-C3")
r(D, "Spawn headless POST /slots/:slot/spawn", "MISSING", "R1", "01-C4")
r(D, "Login to Steam client POST /steam/action login", "MISSING", "R1", "01-C5")
r(D, "Slot 0 'Switch Steam character' (action primary)", "MISSING", "R1", "01-C6")
r(D, "Per-character session controls (Steam/headless/logout) with confirmation + stale guard", "MISSING", "R1", "01-C7, 02-oos")
r(D, "Pending character cards (hosting kind, status labels, delayed help, error)", "MISSING", "R1", "01-C9")
r(D, "Create character dialog POST /roster/create {name,class,look}", "MISSING", "R1", "01-C10")
r(D, "Settings 'Create character' entry", "MISSING", "R1", "01-D12")
r(D, "'Bankboi Active' card (bankboiTransaction)", "MISSING", "R1", "01-C11")
r(D, "Recover Steam handoff POST /steam/recover", "MISSING", "R1", "01-D1")

D = "Realm"
r(D, "Realm header: Current (currentRealm) / 'Mixed realms' / Home, with labels", "PARTIAL", "R2", "01-D5, 01-ch #3")
r(D, "Split-realm per-character list", "MISSING", "R2", "01-D6")
r(D, "Realm select: all realms '(N players)', PVP shown disabled", "PARTIAL", "R2", "01-D7")
r(D, "'Change realm' disabled states + spinner", "MISSING", "R2", "01-D8")
r(D, "Realm operation progress panel", "MISSING", "R2", "01-D9")
r(D, "'Switch realm?' confirmation with Realm Fatigue / Hop Sickness warnings, set-home only when not home", "PARTIAL", "P0-24", "01-D10")
r(D, "Realm switch request POST /realm/switch {realm,setHome}", "PRESENT", "-", "01-D11")

D = "Settings & console"
r(D, "Dashboard state import/export info block (paths, help)", "MISSING", "S2", "01-D2")
r(D, "Export state file", "MISSING", "S2", "01-D3")
r(D, "Import state file (preview, X-State-Preview digest, backup notice)", "MISSING", "S2", "01-D4")
r(D, "Account member grid (portraits, bankbois, live level, 8 slot padding)", "PARTIAL", "S2", "01-D13, 06-oos7")
r(D, "Bankboi default name: seeded from server, trimmed, 3-11 validation, maxLength, Saved/error", "BROKEN", "P0-11", "01-D14, 01-ch #6, 06-#41 (upgraded)")
r(D, "ALData status line Auth/Publish + Check status", "PRESENT", "-", "01-D15 (downgraded), 05-N1")
r(D, "ALData auth-pending banner + 15s /aldata/auth poll", "MISSING", "S2", "01-B11, 01-D15, 05-N4, 06-oos5")
r(D, "ALData key Reveal / Copy", "PRESENT", "-", "01-D16, 05-N2")
r(D, "ALData Generate key", "PRESENT", "-", "01-D17, 05-N2")
r(D, "ALData help text + aldata.error", "PRESENT", "-", "01-D19, 05-N5")
r(D, "Require secure pairing (disabled state, warning, authorized note, inline error)", "PARTIAL", "S2", "01-D20 (endpoint OK per 01-ch)")
r(D, "'Load setup' link to /setup", "MISSING", "S2", "01-D21")
r(D, "Console updates section (version, check, download, restart, automatic toggle)", "MISSING", "S2", "01-D22")
r(D, "Cave of Many Dreams debug instance controls", "MISSING", "S2", "01-D23")
r(D, "Debug-browser link replacing session controls", "MISSING", "S2", "01-C8")
r(D, "PWA-only extras (server-address override, anniversary send in Settings)", "EXTRA", "-", "01-D24")

D = "Logs"
r(D, "Game logs / Dashboard logs tabs (1s)", "PARTIAL", "S3", "01-E1")
r(D, "Game-log category filters (persisted)", "MISSING", "S3", "01-E2")
r(D, "Dashboard-log source select", "MISSING", "S3", "01-E3")
r(D, "Anniversary activity in dashboard logs", "MISSING", "S3", "01-E4")
r(D, "Character filter", "MISSING", "S3", "01-E5")
r(D, "Status line (disconnected / character offline / live)", "MISSING", "S3", "01-E6")
r(D, "Row time, [name]/[source], colour, error red", "PARTIAL", "S3", "01-E7")
r(D, "Chronological latest 1000 + auto-follow", "PARTIAL", "S3", "01-E8")
r(D, "Resizable sidebar", "N/A", "-", "01-E13")

D = "Character card"
r(D, "Portrait (doll HTML / sprite / skin)", "MISSING", "C1", "02-#1")
r(D, "Tracktrix badge on portrait", "MISSING", "C1", "02-#2")
r(D, "Character Stats dialog (formulas, 18 combat stats)", "MISSING", "C1", "02-#3")
r(D, "Online presence dot (seenAt < 10s)", "MISSING", "C1", "02-#4")
r(D, "Level / class / primary stat / realm line", "PRESENT", "-", "02-#5")
r(D, "Per-character ping", "MISSING", "C1", "02-#6")
r(D, "XP meter", "PRESENT", "-", "02-#7")
r(D, "BANKING / BANK QUEUED / STOCKING UP badges", "PRESENT", "-", "02-#8")
r(D, "HP / MP meters", "PRESENT", "-", "02-#9")
r(D, "Gold display (non-merchant)", "PRESENT", "-", "02-#10")
r(D, "Map + coords line with cave relabel", "PARTIAL", "C1", "02-#11")
r(D, "'Awaiting status' placeholder", "PRESENT", "-", "02-#12")
r(D, "Active status section (count, collapse)", "PARTIAL", "C1", "02-#13")
r(D, "Status sprite, ticking countdown, bar, stacks", "PARTIAL", "C1", "02-#14")
r(D, "Condition details dialog", "MISSING", "C1", "02-#15")
r(D, "Statuses visible for merchant characters", "UNREACHABLE", "C1", "02-#16")

D = "Formation"
r(D, "Leader radio POST /formation {leader} only (PWA chip also sends follow:false, never selected)", "BROKEN", "P0-04", "01-C12, 02-#18 (upgraded), 02-ch M9")
r(D, "Follow toggle POST /formation {character,follow} (PWA sends leader:null every tap)", "BROKEN", "P0-04", "01-BROKEN-2, 02-#19, 02-ch (d)")
r(D, "'Following X' hint", "PRESENT", "-", "02-#20")

D = "Events & anniversary"
r(D, "Per-character 'Events (n)' popover POST /formation {character,eventSelections}", "MISSING", "C4", "02-#21, 01-O4")
r(D, "Event schedule labels (LIVE / next / stale / unsupported)", "MISSING", "C4", "02-#22")
r(D, "'Using {leader}'s events' inheritance", "MISSING", "C4", "02-#23")
r(D, "Anniversary settings cog → dialog", "MISSING", "C4", "02-#24, 06-#98")
r(D, "Anniversary live target / map / expiry / next round", "MISSING", "C4", "02-#25")
r(D, "Anniversary failsafe + return-dispatched status", "MISSING", "C4", "02-#26")
r(D, "Per-character ticket stage", "MISSING", "C4", "02-#27")
r(D, "Cake slices grid, complete sets, tradable surplus", "MISSING", "C4", "02-#28")
r(D, "Anniversary auto-chat toggle shows real state, can be turned off", "BROKEN", "P0-10", "02-#29 (upgraded), 01-O3, 02-ch M10")
r(D, "Chat advertisement preview, gating, 'Queued for {merchant}'", "PARTIAL", "C4", "02-#30")
r(D, "Anniversary activity log in dialog", "MISSING", "C4", "02-#31")

D = "Daily dungeons"
for f in ["Dungeon state polling GET /daily-dungeons (1s)",
          "Cave row in Events popover with entry label",
          "Cave settings dialog (participants, eligibility errors, rules)",
          "'Don't leave the Cave for other events' toggle (settings + operationId)",
          "Enter now / Resume visit",
          "Resume ordinary activity (release)",
          "Exit dungeon with confirmation",
          "Retry failed preparation",
          "Return missing participants (recover)",
          "Floor, time remaining, shared gold, Amber, members",
          "Automatic exploration start/stop + progress",
          "Priest recovery status + 'Call Nera' revival",
          "Room/point move buttons",
          "Encounter dialog with votes + paid-vote confirmation",
          "Cave shop inspect + buy with confirmation"]:
    r(D, f, "MISSING", "C5", "02-#32..46")
r(D, "Cave full map with party pins, waypoint placement, native-size", "MISSING", "C5", "02-#47, 06-#100")
r(D, "Escape label 'Escape — exit dungeon' + dungeon actionError", "PARTIAL", "C5", "01-C14 (downgraded), 02-#48 (downgraded), 01-ch X6")

D = "Farming & hunt"
r(D, "Farming mode selector shows saved mode (always 'Auto' today)", "BROKEN", "P0-01", "02-#49 (upgraded)")
r(D, "Badge 'Copy leader' / policy · live effective mode; correct per-character copy", "PARTIAL", "C2", "02-#50")
r(D, "Hunt backup setup (monster + area) on backup_required", "PRESENT", "-", "02-#51")
r(D, "Active farming zone + message (null because legacy=leader check)", "BROKEN", "P0-01", "02-#52 (upgraded)")
r(D, "Hunt status block (status / last status / preparing)", "BROKEN", "C2", "02-#53 (upgraded)")
r(D, "Hunt backup batch countdown + per-member state", "MISSING", "C2", "02-#54")
r(D, "Quest owner + 'Events wait until Daisy reward claims finish'", "BROKEN", "C2", "02-#55 (upgraded)")
r(D, "My quest incl. 'Blacklisted — skipped for Hunt'", "PARTIAL", "C2", "02-#56 (downgraded)")
r(D, "Farming settings dialog owner title, disabled when inherited", "BROKEN", "P0-07", "02-#57")
r(D, "Hunt settings scoped to character, seeded from farmingProfiles[owner], Save not destructive", "BROKEN", "P0-07", "01-ch M1 /hunt-settings, 01-ch X2, 02-#58, 02-ch M4")
r(D, "Hunt blacklist list scoped to character (sprite, label, date, remove)", "BROKEN", "P0-07", "01-ch /hunt-blacklist, 02-#60")
r(D, "Hunt blacklist Clear all with confirmation (correct owner)", "BROKEN", "P0-07", "02-#61")
r(D, "Hunt blacklist labels via huntBlacklistLabel + click → monster details", "MISSING", "C2", "02-#60 note, 02-#63")
r(D, "Add to Hunt blacklist (searchable picker)", "MISSING", "C2", "01-ch X3, 02-#62")
r(D, "Preferred hunt spawns per monster", "MISSING", "C2", "01-ch X4, 02-#59")
r(D, "Passive hunting: field generators toggle POST /rare-hunting", "MISSING", "C2", "02-#64")
r(D, "Passive hunting rules table", "MISSING", "C2", "02-#65")
r(D, "Combat recovery prop (not rendered by dashboard)", "N/A", "-", "02-#66")

D = "Focus & routing"
r(D, "Monster focus picker: 'All' toggle, monsterChoices source, auto-save, empty → []", "BROKEN", "P0-08", "02-#67, 02-ch (c), 02-ch M2")
r(D, "Focus/radius form seeded with real values (every save replaces real focus today)", "BROKEN", "P0-08", "02-ch M3")
r(D, "Clear all focus (X)", "MISSING", "P0-08", "02-#68")
r(D, "Fairy (tinyp) shown disabled with explanation", "BROKEN", "P0-08", "02-#70")
r(D, "Monster search radius (1-10000 validation, no silent reset to 400)", "BROKEN", "P0-08", "02-#72 (upgraded), 01-ch radius note")
r(D, "Per-monster target priority (monsterPriorities)", "MISSING", "C3", "02-#69, 01-O4")
r(D, "Focus display: explicit empty per-character focus kept", "PARTIAL", "C3", "02-#71")
r(D, "Focus header shows effective radius", "MISSING", "C3", "02-ch M8")
r(D, "Radius context/help text", "PARTIAL", "C3", "02-#72 notes")
r(D, "'Find selected monster' disabled for followers", "PARTIAL", "C3", "02-#73 (downgraded)")
r(D, "Leader uses party-monster-travel convoy (isLeader always false today)", "BROKEN", "P0-01", "02-#74 (upgraded), 02-ch M5")
r(D, "Farming-area picker: waypoint pref, map preview/enlarge, legend, MonsterSpawns fallback, label field, monsterChoices list", "PARTIAL", "C3", "02-#74, 02-#51 note, 02-B6")

D = "Map"
r(D, "Live character map (canvas from /map-stream, /maps/:map, native-size dialog)", "MISSING", "C6", "02-#76, 01-M1 maps")

D = "Travel & party actions"
r(D, "Send character to… (known area or exact map/X/Y, validation, error)", "PARTIAL", "C7", "01-C16, 02-#77, 03-#75 (downgraded), 03-ch M3")
r(D, "Return to leader (hidden on leader, disabled when leader offline, error shown)", "BROKEN", "C7", "02-#78 (upgraded), 03-#74")
r(D, "Go home (merchant) sends cmd go-home (PWA sends character-travel main 0,0)", "BROKEN", "P0-23", "02-#79, 03-#73, 03-B5")
r(D, "Send party to town (result surfaced)", "PARTIAL", "C7", "01-C13, 02-#80 (downgraded), 02-ch M7")
r(D, "Escape status polling cadence (1s) + spinner/labels", "PARTIAL", "C7", "02-#81")
r(D, "Error surfacing for travel / go-home / return-leader", "MISSING", "C7", "03-ch M4")
r(D, "Merchant map-travel list labelled 'Send merchant to…' (PWA-only)", "EXTRA", "-", "03-ch M5")

D = "Skills"
r(D, "Skills dialog: search, sprites, id, range label, definition grid", "PARTIAL", "C9", "02-#83, 06-#97")

D = "Combat log"
r(D, "Per-character combat log on character screen (collapsible, colours, last 50, count)", "PARTIAL", "C8", "01-E9, 02-ch M6")
r(D, "Combat log 'Clear history' POST /combat-log/:character/clear", "MISSING", "C8", "01-E10")

D = "Inventory grid"
r(D, "Inventory grid one tile per slot", "PRESENT", "-", "03-#1")
r(D, "Capacity counter occupied/total coloured", "MISSING", "I1", "03-#2")
r(D, "Collapsible Inventory header", "MISSING", "I1", "03-#3")
r(D, "Non-merchant compacted order (layout difference)", "PRESENT", "-", "03-#4, 04-oos4")
r(D, "+level label only when > 0", "PARTIAL", "I1", "03-#5")
r(D, "Coloured stat_type badge", "MISSING", "I1", "03-#6")
r(D, "Quantity badge", "PRESENT", "-", "03-#7")
r(D, "Merchant's Luck clover (item.m)", "MISSING", "I1", "03-#8")
r(D, "In-progress upgrade/compound overlay (from→to, chance)", "MISSING", "I1", "03-#9")
r(D, "Action banner priority/variants (item-action-banner port)", "PARTIAL", "I1", "03-#10")
r(D, "Banner tooltip (NPC sale state/error/retry, conflicts)", "MISSING", "I1", "03-#11")
r(D, "Tile border coloured by banner", "PARTIAL", "I1", "03-#12")
r(D, "Merchant hover/long-press tooltip (suggested price, decon, NPC state)", "MISSING", "I1", "03-#13")
r(D, "'Loading inventory…' state", "PARTIAL", "I1", "03-#15")
r(D, "Tap opens item details", "PRESENT", "-", "03-#16")
r(D, "Tile sprite fallback to name / live meta.sprite", "PARTIAL", "I1", "03-ch M11")
r(D, "Inventory upgrade banner '+L → +T'", "BROKEN", "P0-01", "04-#8")
r(D, "Compound group banner", "BROKEN", "P0-01", "04-#28")
r(D, "Stat scroll banner", "BROKEN", "P0-01", "04-#38")
r(D, "Auto compound pending banner", "MISSING", "I1", "04-#30")
r(D, "Auto exchange banner", "MISSING", "I1", "04-#57")
r(D, "Auto stand banner on inventory tiles", "MISSING", "I1", "05-J7")

D = "Item menu"
r(D, "Equip only for equipment", "PARTIAL", "I2", "03-#17")
r(D, "Use / 'Use elixir' only when usable", "PARTIAL", "I2", "03-#18")
r(D, "Compare with equipped", "PRESENT", "-", "03-#19")
r(D, "Compare slot submenu (Main/Off hand, Ring/Earring 1/2 with equipped name)", "MISSING", "I2", "03-#20")
r(D, "Deliver to… targets online, not self, no bankbois", "PARTIAL", "I2", "03-#21")
r(D, "Deliver merchant+equipment Don't equip / Equip", "PRESENT", "-", "03-#22")
r(D, "Stat scroll submenu (costs, owned/required, wiring)", "PRESENT", "-", "03-#23, 04-#36")
r(D, "Stat scroll pending-mark trigger label", "PARTIAL", "U2", "03-#23, 04-#37")
r(D, "Auto exchange row disabled when marked (server toggle silently removes rule)", "BROKEN", "P0-17", "03-#24, 04-#56, 04-ch (a)")
r(D, "Mark for bank disabled once marked", "PARTIAL", "I2", "03-#25")
r(D, "Auto mark for bank (only with merchant, disabled once set)", "PARTIAL", "I2", "03-#26 (downgraded)")
r(D, "Mark for stand / Edit stand listing (defaults, 16/16 guard, never shrink qty)", "BROKEN", "P0-14", "03-#27, 03-B3, 03-ch M10")
r(D, "Auto mark for stand price default (empty → price 0 → 400)", "PARTIAL", "P0-14", "03-#28")
r(D, "Mark for upgrade tier submenu with '· N tiers'", "PARTIAL", "U2", "03-#29, 04-#1")
r(D, "Auto mark for upgrade (current tier disabled, label)", "PARTIAL", "U2", "03-#31, 04-#13")
r(D, "Buy another level 0", "PRESENT", "-", "03-#33, 04-#6")
r(D, "Mark for compounding hidden when grouped", "PARTIAL", "U2", "03-#34, 04-#27")
r(D, "Auto compound submenu label 'to +N', hidden when level ≥ min(7,max)", "PARTIAL", "U2", "03-#35 (downgraded), 04-#29")
r(D, "Auto compound target capped at 7 (else command falls through)", "BROKEN", "P0-25", "04-ch row 29, 04-ch M7")
r(D, "Mark for merchant (non-merchant only, disabled once marked)", "PARTIAL", "I2", "03-#36")
r(D, "Auto mark for merchant (non-merchant only)", "PARTIAL", "I2", "03-#37")
r(D, "Clear all marks conditional + tooltip (inventory)", "PARTIAL", "I2", "03-#43 (downgraded), 03-ch M12")
r(D, "Clear marks also removes auto-exchange rule", "PRESENT", "-", "04-#60")
r(D, "Merchant weapon banner", "MISSING", "I2", "03-#44")
r(D, "Actions hidden when no merchant configured (auto-bank, Sell NPC, auto NPC, compound, exchange, stand)", "PARTIAL", "I2", "03-ch M6")
r(D, "Auto-deconstruct / auto-bank disabled when rule exists", "MISSING", "I2", "03-ch M7")
r(D, "'Update auto sell to NPC…' / 'Update auto mark for stand…' labels", "MISSING", "I2", "03-ch M8")

D = "Deconstruction"
r(D, "Mark for deconstruction gated by deconstructionCatalog", "PARTIAL", "I3", "03-#38")
r(D, "Deconstruction confirmation dialog (rewards %, cost, titles)", "MISSING", "I3", "03-#39")
r(D, "Auto mark for deconstruction with confirmation", "PARTIAL", "I3", "03-#40")
r(D, "Pending deconstruction marks list with Retry / remove by id", "MISSING", "I3", "03-#59")
r(D, "Bank 'Mark for deconstruction' confirmation (+ unreachable until config)", "BROKEN", "I3", "06-#16 (upgraded)")

D = "NPC sale"
r(D, "Sell to NPC… quantity sheet defaulting to stack, proceeds, ack (character + merchant)", "BROKEN", "P0-15", "01-F4, 03-#41, 03-B2")
r(D, "Bank Sell to NPC dialog (editable qty, always confirm)", "PARTIAL", "P0-15", "06-#18")
r(D, "Auto sell to NPC on merchant omits character (else dead rule + wipes other rules)", "BROKEN", "P0-16", "03-#42, 03-B1, 03-ch M2")
r(D, "Remove auto-NPC rule from merchant list (no character)", "BROKEN", "P0-16", "03-#69")
r(D, "Automatic NPC-sale confirmation dialog ('You will receive Xg')", "PARTIAL", "I4", "01-F3")
r(D, "Auto NPC sales list incl. manual npcSaleMarks (owner, qty, state, error)", "PARTIAL", "I4", "03-#57")
r(D, "Remove manual NPC-sale mark by id", "MISSING", "I4", "03-#58")

D = "Equipment"
r(D, "Equipment excludes trade* stand slots (Unequip pulls listing off stand)", "BROKEN", "P0-13", "03-#45, 03-B4, 03-ch M1")
r(D, "All 15 fixed slots with 'Empty' tiles", "PARTIAL", "I5", "03-#46 (mostly missing)")
r(D, "Slot labels ('Earring 1')", "PARTIAL", "I5", "03-#47")
r(D, "Level / stat_type / mluck badges on equipped", "PARTIAL", "I5", "03-#48")
r(D, "Set progress badge", "MISSING", "I5", "03-#49")
r(D, "Equipment upgrade/stat banner", "BROKEN", "P0-01", "03-#50, 04-#9")
r(D, "Equipped stat-scroll banner (statScrolls passed as [])", "MISSING", "I5", "04-#39")
r(D, "Unequip (not elixir)", "PRESENT", "-", "03-#51")
r(D, "Elixir disabled 'Active elixir effect'", "PARTIAL", "I5", "03-#52")
r(D, "Equipped Mark for upgrade (labels, offering rows)", "PARTIAL", "U2", "03-#53, 04-#2, 03-ch M9")
r(D, "Equipped Auto mark for upgrade", "PARTIAL", "U2", "04-#14")
r(D, "Clear all marks on equipped (conditional)", "PARTIAL", "I2", "03-#54 (downgraded)")
r(D, "Click equipped opens details", "PRESENT", "-", "03-#55")
r(D, "Equipped 'Buy copy' (dashboard never offers)", "EXTRA", "-", "03-#56, 04-#7")

D = "Auto-rule lists"
r(D, "Auto deconstruction rules scoped to ruleOwner (shared rules)", "PARTIAL", "F1", "03-#60, 04-oos5")
r(D, "Auto stand marks list + remove", "PRESENT", "-", "03-#61, 05-J8")
r(D, "Auto upgrades list (all owners, '+a → +b', owner, count)", "BROKEN", "I8", "03-#62, 04-#16")
r(D, "Edit auto-upgrade target tiers", "MISSING", "I8", "03-#63, 04-#17")
r(D, "Edit auto-upgrade remaining quantity (∞ / Completed)", "MISSING", "I8", "03-#63, 04-#18")
r(D, "Remove one auto-upgrade rule with confirm + error", "PARTIAL", "I8", "04-#19, 03-#68")
r(D, "Clear all auto upgrades (button hidden: list empty)", "BROKEN", "P0-01", "04-#20")
r(D, "Auto compounds list (owner, target, qty)", "BROKEN", "I8", "04-#31")
r(D, "Edit auto-compound target (1-7)", "MISSING", "I8", "03-#64, 04-#32")
r(D, "Edit auto-compound quantity", "MISSING", "I8", "03-#64, 04-#33")
r(D, "Remove auto compound", "PRESENT", "-", "04-#34")
r(D, "Clear all auto compounds", "BROKEN", "P0-01", "04-#35")
r(D, "Auto merchant marks list", "PRESENT", "-", "03-#65")
r(D, "Auto bank marks scoped to ruleOwner", "PARTIAL", "F1", "03-#66")
r(D, "Per-section Clear all with confirmation", "PRESENT", "-", "03-#67")
r(D, "AutoMarksSection remove/clear surfaces errors", "MISSING", "I8", "04-oos7")

D = "Item details"
r(D, "Header sprite/name/'character · slot N'", "PRESENT", "-", "03-#76")
r(D, "'Add to stand' from details (stand-full guard)", "PARTIAL", "I6", "03-#77")
r(D, "'Add to WTB' from details with preview level", "PARTIAL", "I6", "03-#78")
r(D, "Tracktrix bonuses for tracker/supercomputer", "MISSING", "I6", "03-#79")
r(D, "Explanation text", "PRESENT", "-", "03-#80")
r(D, "Buy from / Sell to NPC values", "PRESENT", "-", "03-#81")
r(D, "Eligible classes + hands-required line", "PARTIAL", "I6", "03-#82")
r(D, "Level stat preview slider", "PRESENT", "-", "03-#83")
r(D, "Compare popover: any party character → slot", "MISSING", "I6", "03-#84")
r(D, "Stats grid ranking, equip_slot row, hide type", "PARTIAL", "I6", "03-#86")
r(D, "propertiesAtLevel semantics (keep server-only properties)", "PARTIAL", "I6", "04-#70")
r(D, "Set bonus with clickable pieces", "PRESENT", "-", "03-#87")
r(D, "Ingredient in", "PRESENT", "-", "03-#88")
r(D, "Craftable", "PRESENT", "-", "03-#89")
r(D, "Monster drops Sort select (Name/Percentage)", "PARTIAL", "I6", "03-#92")
r(D, "Back-navigation trail", "PRESENT", "-", "03-#94")
r(D, "Live-instance meta merged over catalog meta", "PARTIAL", "I6", "03-#95")

D = "Gear comparison"
r(D, "Open from 'Compare with equipped'", "PRESENT", "-", "03-#96, 06-#99")
r(D, "Full character projection (HP…Output) with deltas", "PARTIAL", "I7", "03-#97")
r(D, "Character doll image", "MISSING", "I7", "03-#98")
r(D, "Set changes section (GAINED/LOST)", "MISSING", "I7", "03-#99")
r(D, "Stat-scroll preview per side", "PRESENT", "-", "03-#100")
r(D, "Independent preview-level sliders", "PRESENT", "-", "03-#101")

D = "Catalog"
r(D, "Catalog reachable", "PRESENT", "-", "03-#102, 06-#83")
r(D, "Equipment-only scope", "PARTIAL", "I9", "03-#103, 06-#84")
r(D, "Search name/id/set", "PARTIAL", "I9", "03-#104, 06-#85")
r(D, "Sort (25) + sorted stat value", "MISSING", "I9", "03-#105, 06-#86")
r(D, "Type filter chips", "MISSING", "I9", "03-#106, 06-#87")
r(D, "Class filter chips + 'Exclusive gear'", "MISSING", "I9", "03-#107, 06-#88")
r(D, "Result count / sorted-by line", "MISSING", "I9", "03-#108, 06-#89")
r(D, "Tile type · T{tier} · set · stat", "PARTIAL", "I9", "03-#109, 06-#90")
r(D, "Inspect → details with WTB action", "PARTIAL", "I9", "03-#110, 06-#91")
r(D, "Incremental rendering (120-row batches)", "MISSING", "I9", "06-#92")
r(D, "Catalog comparison mode (A + ≤3, from details 'From catalog')", "MISSING", "I9", "03-#85, 03-#111, 04-#71, 06-#93")
r(D, "Catalog comparison table (level sliders, stat scroll, deltas, abilities)", "MISSING", "I9", "03-#111, 06-#94")

D = "Upgrades & offerings"
r(D, "Upgrade with Primling/Essence/Primordial + confirm (inventory & equipped)", "MISSING", "U1", "03-#30, 04-#3")
r(D, "Offering stock state (upgradeOfferingStock)", "MISSING", "U1", "04-#4")
r(D, "Server upgrade preview panel POST /upgrade-preview (+Refresh, 2s poll)", "MISSING", "U1", "04-#5, 01-M1")
r(D, "'Add upgrade rule' from item (prefilled)", "MISSING", "U1", "03-#32, 04-#15")
r(D, "Upgrade offering rules list", "PRESENT", "-", "03-#70, 04-#21")
r(D, "Edit offering rule", "PRESENT", "-", "04-#22")
r(D, "Remove offering rule", "PRESENT", "-", "04-#23")
r(D, "Clear all offering rules (two-click)", "MISSING", "U1", "04-#24")
r(D, "Add offering rule dialog: overlap / ceiling validation, from item", "PARTIAL", "U1", "04-#25")

D = "Lucky slot"
r(D, "Lucky slot summary", "PRESENT", "-", "04-#40")
r(D, "Lucky statistics dialog counts + explanatory text", "PARTIAL", "U3", "04-#41")
r(D, "Lucky slot outline in merchant grid + menu", "MISSING", "U3", "03-#14, 04-#42")
r(D, "Merge live local evidence stream", "PARTIAL", "U3", "04-#43")
r(D, "Verified-slot validation", "PRESENT", "-", "04-#44")

D = "Exchange"
r(D, "Exchange catalog search + owned/required + Add", "PRESENT", "-", "04-#45, 05-H10")
r(D, "Owned counts include bankboi storage (exchange + craft)", "BROKEN", "M10", "04-#46 (fix corrected), 05-H8")
r(D, "Currency grouping / Choose / choices panel", "PRESENT", "-", "04-#47, 05-H10")
r(D, "Exchange cart + Exchange all POST /merchant/exchange-order", "PRESENT", "-", "04-#48, 05-H11")
r(D, "409 missing-materials detail (exchange + order)", "PARTIAL", "M10", "04-#49, 05-H9")
r(D, "Exchange rules overlay (gear, 'N required per exchange', potential results)", "PARTIAL", "M11", "04-#50 (downgraded), 05-H12")
r(D, "Tap exchange tile → item details with 'Add'", "MISSING", "M11", "04-#51, 05-H14, 03-ch M14")
r(D, "Nested exchange drill-down", "MISSING", "M11", "04-#52")
r(D, "'Mark multiple' bulk staging (bank/stand/upgrade/npc)", "MISSING", "M11", "04-#53, 05-H13")
r(D, "Reward-tile banners", "MISSING", "M11", "04-#54")
r(D, "Reward-tile automatic-action context menu", "MISSING", "M11", "03-#91, 04-#55")
r(D, "Item details 'Exchange price'", "PRESENT", "-", "04-#61")
r(D, "Item details fixed reward opens the reward (navigates to itself today)", "BROKEN", "M11", "04-#62")
r(D, "Item details table rewards with chance", "PRESENT", "-", "04-#63")
r(D, "'Reward in' sources", "PRESENT", "-", "04-#64")
r(D, "'Rewards' heading for boxes, cosmo/sixcake notes", "PARTIAL", "M11", "03-#90, 04-#65")
r(D, "Exchange sections follow preview level", "PARTIAL", "M11", "04-#66")

D = "Commerce"
r(D, "Buy/Craft/Exchange buttons", "PRESENT", "-", "05-C1")
r(D, "Buy catalog search + Add", "PRESENT", "-", "05-H1")
r(D, "Buy cart qty ≤ 9999, target +level", "PARTIAL", "M10", "05-H2")
r(D, "Buy cart target level for upgradeables", "PRESENT", "-", "04-#68")
r(D, "90% budget line + 'Gold (est)' via upgradeEstimate", "MISSING", "M10", "04-#69, 05-H3")
r(D, "Buy submit POST /merchant/order", "PRESENT", "-", "05-H4")
r(D, "Craft list + ingredient totals", "PRESENT", "-", "05-H5")
r(D, "Craft gold total incl. ingredient purchases", "MISSING", "M10", "05-H6")
r(D, "Recipe preview (per-material owned/missing/buy)", "MISSING", "M10", "05-H7")

D = "Merchant card & queue"
r(D, "Collapsible 'Merchant logistics · N queued' + 'No queued work'", "PARTIAL", "M1", "05-A1, 05-ch X7")
r(D, "Human job labels (merchantJobLabel + routineFor)", "PARTIAL", "M1", "05-A2, 04-ch M4")
r(D, "Priority prefix P{n}", "MISSING", "M1", "05-A3")
r(D, "Target suffix (suppressed for giveaway)", "PARTIAL", "M1", "05-A4 (downgraded)")
r(D, "Status column: deferred reason, phase, retryAt, pauseReason", "PARTIAL", "M1", "05-A5, 04-ch oos")
r(D, "Retry only when realmRetryExhausted", "PARTIAL", "M1", "05-A6 (downgraded), 04-ch oos")
r(D, "Cancel: confirm for automatic routines, hidden for fishing/mining/current, 'undo pending intent' hint", "BROKEN", "P0-22", "04-#59, 04-ch M2, 04-ch M3, 05-A7, 05-BR-7")
r(D, "Merchant's Luck upkeep row", "MISSING", "M1", "05-A8")
r(D, "Current job first", "PRESENT", "-", "05-A9")
r(D, "Activity log: time, level colour, details", "PARTIAL", "M1", "01-E11, 05-B1")
r(D, "Clear stale orders shows removed counts", "PARTIAL", "M1", "05-B2, 01-O5")
r(D, "Clear history", "PRESENT", "-", "01-E12, 05-B3")
r(D, "Cleanup / clear-history inline result text", "PARTIAL", "M1", "05-ch X6")
r(D, "Donate gold with XP preview + description + inline error", "PARTIAL", "M1", "05-C2, 06-#96")
r(D, "Join giveaway: realm Select + online-player picker", "PARTIAL", "M1", "01-F1, 05-C3")
r(D, "Send to party group picker (/bank-party {group})", "PARTIAL", "M1", "05-C4")
r(D, "Force stand toggle reflects server state (can't be turned off today)", "BROKEN", "P0-10", "05-C5 (upgraded), 01-O1, 05-ch X4")
r(D, "Routines button", "PRESENT", "-", "05-C6")
r(D, "Mining/Fishing toggles", "PRESENT", "-", "05-C7")
r(D, "Mining/Fishing readiness (Ready / cooldown / No tool)", "MISSING", "M1", "05-C8")
r(D, "Clear job queue", "PRESENT", "-", "05-C9")
r(D, "'Send merchant to…' manual visit (/command {character:target,type:'bank'})", "MISSING", "M1", "03-#72, 03-B6, 05-C10")
r(D, "Gold target 'Exchange gold and items with bank' (cmd bank)", "PARTIAL", "M1", "02-#82, 05-F3")
r(D, "Gold target offered for every character (dashboard: merchant only)", "EXTRA", "-", "02-ch M11, 05-oos5")
r(D, "Hardcoded Patinder 'Clear stuck production attempt' button", "BROKEN", "P0-21", "01-ch X5, 04-#73, 04-ch (e), 05-oos3")

D = "Routines"
r(D, "Routine label set incl. deliveries, withdrawals, upgrade preview, manual/automatic exchange (no 'exchange')", "BROKEN", "P0-06", "04-#58, 04-#72, 05-D1, 06-#24 label")
r(D, "Enable checkboxes: automatic keys + fishing/mining seeded from gatheringModes", "BROKEN", "P0-06", "05-D2, 05-BR-2")
r(D, "Seed draft from server (Save posts 50 / true for everything today)", "BROKEN", "P0-06", "01-F5, 05-D3, 04-ch (b)")
r(D, "Deliveries/withdrawals rows disabled + priority dropped when trip off", "MISSING", "P0-06", "05-D5")
r(D, "Save body POST /merchant/routine-priorities", "PARTIAL", "P0-06", "05-D8")
r(D, "Seed on open only (no late overwrite of edits)", "PARTIAL", "P0-06", "05-ch X8")
r(D, "Header 'N/M enabled'", "PARTIAL", "M3", "05-D4")
r(D, "Priority input 0-100", "PRESENT", "-", "05-D6")
r(D, "Reorder skips disabled routines", "PARTIAL", "M3", "05-D7")

D = "Merchant settings"
r(D, "Settings entry/sheet", "PARTIAL", "M2", "05-E1")
r(D, "Bank sort 'Sort on next visit' + status", "PRESENT", "-", "06-#22")
r(D, "Bank sorting mode radio", "PRESENT", "-", "05-E2, 06-#23")
r(D, "Bank sort help text + error display", "PARTIAL", "M2", "06-#22 note, 06-ch M12")
r(D, "Maximum number to buy at once (buyUpgradeBatchSize)", "MISSING", "M2", "01-O5, 04-#67, 05-E3")
r(D, "Merchant stand location X/Y", "MISSING", "M2", "05-E4")
r(D, "Marked deliveries create merchant jobs", "MISSING", "M2", "05-E5")
r(D, "Marked withdrawals create merchant jobs", "MISSING", "M2", "05-E6, 06-#24")
r(D, "Gold collection threshold seeded/validated (writes threshold:0 today)", "BROKEN", "P0-12", "01-F6, 01-ch #8, 05-E7")
r(D, "Item collection threshold 1-42 seeded/validated", "BROKEN", "P0-12", "01-F6, 05-E8")
r(D, "Collection settings explanatory text + inline errors", "PARTIAL", "M2", "05-E7, 05-E8")

D = "Restock"
r(D, "Restock HP/MP min/max (defaults 5/20/0/0, no zeroing of untouched fields)", "BROKEN", "P0-09", "05-G1 (upgraded), 05-ch X3")

D = "Stand"
r(D, "'Items for sale · N/16' + Stand open/closed", "MISSING", "M4", "05-I2")
r(D, "Sale rows reconciled vs trade slots (Live/Paused/Queued, unmanaged rows)", "MISSING", "M4", "05-I3")
r(D, "Sale tile badges (sprite, level, stat, clover, qty)", "PARTIAL", "M4", "05-I4")
r(D, "Suggested-price tooltip", "MISSING", "M4", "05-I5")
r(D, "Stand price edit keeps bankPack (bank listing converted today)", "BROKEN", "P0-14", "05-I6 (upgraded), 05-ch X5")
r(D, "Stand Remove sends id+bankPack, two-step confirm (silent no-op today)", "BROKEN", "P0-14", "05-I7, 05-BR-4, 03-ch #27")
r(D, "Native buy orders section (priority, use-stand, cancel)", "MISSING", "M4", "05-I8")
r(D, "Inspect item from stand row", "MISSING", "M4", "05-I9")

D = "Stand dialog"
r(D, "Dialog context: Buy-from-NPC price, current number on market", "MISSING", "M5", "01-F2, 05-J1")
r(D, "13 price presets", "MISSING", "M5", "01-F2, 05-J2")
r(D, "Quantity input for stacks (default stack)", "MISSING", "P0-14", "01-F2, 05-J3")
r(D, "'Mark all for stand' (markAll:true; bank 'Mark all' mislabelled today)", "BROKEN", "P0-14", "01-F2, 05-J4, 06-#12, 06-B2")
r(D, "Inline stand error", "PARTIAL", "M5", "05-J5")
r(D, "Automatic stand variant: presets, existing rule prefill, 'Update'", "PARTIAL", "M5", "05-J6")
r(D, "16-slot guard when not editing", "MISSING", "M5", "01-F2")

D = "Market"
r(D, "Status banner (unavailable / loading / not configured + Go to setup)", "MISSING", "M6", "05-K2")
r(D, "Tabs with counts: Live WTS / Live WTB / Classifieds / Ponty", "PARTIAL", "M6", "05-K3")
r(D, "Search item/seller/server/map", "MISSING", "M6", "05-K4")
r(D, "WTS filters (deals, bad deals, unaffordable, blacklisted)", "MISSING", "M6", "05-K5")
r(D, "WTS grouping + fresh-first sort", "MISSING", "M6", "05-K6")
r(D, "WTS row details, deal colouring, stale dimming", "PARTIAL", "M6", "05-K7")
r(D, "WTS buy: qty + All + confirmation + stale→Make WTB", "PARTIAL", "M6", "05-K8")
r(D, "Live WTB tab + Sell POST /merchant/aldata-sale + List", "MISSING", "M6", "05-K9, 01-M1")
r(D, "Classifieds tab", "MISSING", "M6", "05-K10")
r(D, "Ponty tab grouping/freshness/'Matches WTB'/error", "PARTIAL", "M6", "05-K11")
r(D, "Ponty purchase routed to /merchant/ponty-order (Ponty rows have no source)", "BROKEN", "P0-19", "05-K12, 05-BR-3")
r(D, "Inspect item from any market row", "MISSING", "M6", "05-K15")
r(D, "Purchase result handling (busy, inline error, no double tap)", "PARTIAL", "M6", "05-ch X9")
r(D, "Player-stand search & buy (dashboard dialog is dead code; results need config standSearch)", "EXTRA", "-", "05-K16, 01-M2, 01-O10")

D = "WTB"
r(D, "Active WTB panel inside market", "PARTIAL", "M7", "05-K13")
r(D, "New WTB item picker", "PRESENT", "-", "05-K14")
r(D, "WTB list filter + count + empty texts", "PARTIAL", "M7", "05-L1")
r(D, "Row inspect + '· +N minimum'", "PARTIAL", "M7", "05-L2")
r(D, "Inline field edits with editField + bidRevision", "PARTIAL", "M7", "05-L3")
r(D, "Use-stand / accept-higher toggles + explanations, Auto badge, problems", "PARTIAL", "M7", "05-L4")
r(D, "Cancel with 'Really cancel?'", "PARTIAL", "M7", "05-L5")
r(D, "'Make room' replacement dialog on 409 occupants", "MISSING", "M7", "05-L6")
r(D, "WTB dialog fields (priority clamp 100)", "PRESENT", "-", "05-L7")
r(D, "Clearing priorityOverride (null always sent)", "BROKEN", "P0-18", "05-L8, 05-BR-5")
r(D, "15 price presets", "PARTIAL", "M7", "05-L9")
r(D, "Existing price prefill only at same minimumQuality", "PARTIAL", "M7", "05-L10")
r(D, "Entry points: item details, stand buy-order, market Make/Add to WTB", "MISSING", "M7", "05-L11, 03-#78")

D = "Marketplace settings"
r(D, "Auto-fill empty stand slots (/merchant/native-stand configure)", "MISSING", "M8", "05-M1")
r(D, "Enable blacklisting unavailable merchants", "MISSING", "M8", "05-M2")
r(D, "Manual blacklist add", "MISSING", "M8", "05-M3")
r(D, "Strike records list + clear", "MISSING", "M8", "05-M4")
r(D, "Clear all blacklist (two-step)", "MISSING", "M8", "05-M5")

D = "Shared rules"
r(D, "Configured merchant (merchantCharacter) used instead of ctype==='merchant' everywhere", "BROKEN", "F1", "03-oos, 03-ch M13, 04-ch M6, 06-oos1")
r(D, "Shared-rule conflicts panel POST /merchant/rule-conflict", "MISSING", "M9", "03-#71, 05-O1")
r(D, "Incompatible-rules notice", "MISSING", "M9", "05-O2")

D = "Bank"
r(D, "No snapshot empty state", "PRESENT", "-", "06-#2")
r(D, "Search (name/id/definition name) with dimming", "MISSING", "B1", "06-#3, 06-ch M10")
r(D, "Pack header occupied/total", "PRESENT", "-", "06-#4")
r(D, "stat_type badge", "MISSING", "B1", "06-#5a")
r(D, "Merchant's Luck clover", "MISSING", "B1", "06-#5b")
r(D, "Auto-stand banner", "MISSING", "B1", "06-#5c")
r(D, "RESERVED overlay on items1 35-41", "MISSING", "B1", "06-#5d")
r(D, "Co-existing mark indicators (withdraw border, $, NPC) with same() identity", "BROKEN", "B1", "06-#5e (upgraded)")
r(D, "Tap tile → full item details (bank source)", "MISSING", "B1", "06-#7")
r(D, "Mark/Unmark for withdrawal to configured merchant (offline OK)", "BROKEN", "F1", "06-#8, 06-B1")
r(D, "Mark all for withdrawal", "BROKEN", "F1", "06-#9")
r(D, "Withdraw double-tap guard (2nd tap removes mark)", "BROKEN", "P0-20", "06-ch M3")
r(D, "Auto-bank 409 confirm → retry with removeAutoBankMark", "MISSING", "B1", "06-#10, 06-B6")
r(D, "Bank Mark for stand (price default, qty default, unmark)", "BROKEN", "P0-14", "06-#11 (upgraded), 06-ch M4")
r(D, "Bank auto mark for stand", "MISSING", "B1", "06-#13")
r(D, "Bank Mark for upgrade (withdraw upgradeTiers)", "MISSING", "B1", "04-#10, 06-#14")
r(D, "Bank Auto mark for upgrade (slot -1)", "MISSING", "B1", "04-#11, 06-#15")
r(D, "Bank 'Add upgrade rule'", "MISSING", "B1", "04-#12")
r(D, "Bank auto mark for deconstruction", "MISSING", "B1", "06-#17")
r(D, "Bank auto sell to NPC", "MISSING", "B1", "06-#19")
r(D, "Bank clear all marks", "MISSING", "B1", "06-#20")
r(D, "Disabled states (no merchant, item.l, stand full)", "PARTIAL", "B1", "06-#21")

D = "Bank floors & vaults"
r(D, "Floor names", "PARTIAL", "B2", "06-#25")
r(D, "Floor access status", "MISSING", "B2", "06-#26")
r(D, "Unlock with key, owned count, disabled at 0", "PARTIAL", "B2", "06-#27")
r(D, "Gold unlock only on accessible floors", "PARTIAL", "B2", "06-#28 (downgraded)")
r(D, "Vault notices", "MISSING", "B2", "06-#29")
r(D, "Unlock confirmation text names merchant / key consumed", "PARTIAL", "B2", "06-#30, 06-ch M6")
r(D, "Unlock wiring POST /bank/unlock", "PRESENT", "-", "06-#31")
r(D, "Vault gold cost display", "PRESENT", "-", "06-#32")
r(D, "Unlock disabled without configured merchant", "MISSING", "B2", "06-ch M5")
r(D, "'Additional bank storage' lists every floor", "PARTIAL", "B2", "06-ch M7")

D = "Bankbois"
r(D, "Section header 'N staged or waiting' (bankboiQueue)", "MISSING", "B3", "06-#33")
r(D, "Create bankboi POST /bankbois/create", "MISSING", "B3", "06-#34, 01-M1")
r(D, "First-bankboi confirm (reserve 7 slots)", "MISSING", "B3", "06-#35")
r(D, "Prefix-required alert / disabled create", "MISSING", "B3", "06-#36")
r(D, "Bankboi card (name, mode·phase, occupied/42, error)", "MISSING", "B3", "06-#37")
r(D, "Delete bankboi (empty only, two-step)", "MISSING", "B3", "06-#38, 01-M1")
r(D, "Bankboi 42-slot grid with full context menu", "MISSING", "B3", "06-#39")
r(D, "'No bankbois yet' empty text", "MISSING", "B3", "06-#40")

D = "Mail"
r(D, "Inbox row subject/From/date/attachment status", "PARTIAL", "B4", "06-#44")
r(D, "Refresh POST /mail/refresh", "MISSING", "B4", "06-#45 (lower severity)")
r(D, "'Mail may be out of date' / loading / empty", "MISSING", "B4", "06-#46")
r(D, "Message detail from → to · date, pre-wrap", "PARTIAL", "B4", "06-#47")
r(D, "Attachment tile sprite/level/qty + inspect", "PARTIAL", "B4", "06-#48")
r(D, "Attachment status labels ('pending' shows collected today)", "BROKEN", "B4", "06-#49 (partly downgraded)")
r(D, "Collect disabled while queued/collecting + errors", "PARTIAL", "B4", "06-#50")
r(D, "Delete message two-step POST /mail/delete", "MISSING", "B4", "06-#51")
r(D, "Reply", "MISSING", "B4", "06-#52")
r(D, "Compose limits + disable rules", "PARTIAL", "B4", "06-#53")
r(D, "Attachment picker (merchant, bank, bankbois)", "MISSING", "B4", "06-#54, 01-O6")
r(D, "Attachment quantity", "MISSING", "B4", "06-#55, 01-O6")
r(D, "Postage estimate GET /mail/postage", "MISSING", "B4", "06-#57")
r(D, "Two-step send", "MISSING", "B4", "06-#58")
r(D, "Mail outcome status (collection, collectionError)", "MISSING", "B4", "06-ch M8")
r(D, "Write message / Cancel / Remove attachment footer", "PARTIAL", "B4", "06-ch M9")
r(D, "ALData 'Prepare mail' through composer with postage + pending", "PARTIAL", "B4", "01-D18, 05-N3")
r(D, "decodeMailInbox (old coordinators only)", "N/A", "-", "06-#60 (refuted)")

D = "Bestiary"
r(D, "Tracktrix bonuses popover", "MISSING", "X1", "06-#63")
r(D, "Map filter chips", "MISSING", "X1", "06-#64")
r(D, "Search", "MISSING", "X1", "06-#65")
r(D, "Sort + asc/desc", "MISSING", "X1", "06-#66")
r(D, "'Tracktrix data unavailable' notice", "MISSING", "X1", "06-#67")
r(D, "Card threat", "PARTIAL", "X1", "06-#69")
r(D, "Card achievements / score / high score", "MISSING", "X1", "06-#70")
r(D, "Monster details dialog (unified with item drill-in)", "PARTIAL", "X1", "02-#75, 03-#93, 06-#71, 06-#80")
r(D, "G.monsters.ID line", "MISSING", "X1", "06-#72")
r(D, "Navigate to monster (non-Phoenix; tinyp disabled)", "MISSING", "X1", "02-#75, 06-#73")
r(D, "Monster achievements panel", "MISSING", "X1", "06-#74")
r(D, "Recorded spawns with restrictions", "MISSING", "X1", "06-#75, 02-#75")
r(D, "Definition grid", "MISSING", "X1", "06-#76")
r(D, "Drop rate via formatDropRate (250.0000% / 0.0000% today)", "BROKEN", "X1", "06-#77 (severity up)")
r(D, "Zone & world drops", "MISSING", "X1", "06-#78")
r(D, "Click drop → item details", "PARTIAL", "X1", "06-#79")
r(D, "Drops order (server order)", "PARTIAL", "X1", "06-ch M11")
r(D, "monsterAchievements per character aggregated", "MISSING", "F2", "06-#81")
r(D, "tracktrix per character", "MISSING", "F2", "06-#82")

D = "Infrastructure"
r(D, "API post() returns parsed body + status + code (occupants, missing, counts, auto_bank_confirmation_required)", "BROKEN", "F3", "05-oos4, 05-ch (f), 06-ch (b)")
r(D, "e2e mock honours section, strips config from core, mirrors server semantics", "BROKEN", "P0-03", "01-O9, 02-ch M13, 03-ch M15, 05-ch X10, 06-ch 7")
r(D, "TEMPORARY coreFetchDebug banner shipped", "BROKEN", "P0-21", "02-ch M12, 02-oos, 03-oos")
